INSERT INTO t_poder (podtipo, poddescripcion) VALUES
("Aspecto físico no-humano","El poder puede provenir de un rasgo no-humano de la constitución física del sujeto (una criatura completamente formada por fuego, o roca, por ejemplo)."),
("Tecnopatía","Habilidad para manipular tecnología. Puede manifestarse como una forma particular de manipulación eléctrica, una forma especial de polimorfismo, o incluso una forma especial de percepción extrasensorial."),
("Tecnoquinesis","Habilidad para construir o formar máquinas através de un material. Esto se ha visto en películas como Escuela de Súper Héroes, donde la villana podía con un bloque de metal, crear una arma letal o en X-Men donde una persona transforma su brazo en una máquina de reparación"),
("Ciberpatía","Habilidad para conectarse a Internet inalambricamente, mandar mensajes e infectar con virus a las computadoras, todo desde la mente. Hay mayor recepción cuando se encuentra en lugares libres y a gran altura."),
("Telequinesis","Habilidad para manipular y controlar objetos con la mente, frecuentemente de forma no visibles para el ojo humano normal. Una telequinesis extremadamente poderosa podría controlar incluso átomos individuales."),
("Telequinesis orbitacional","Habilidad para manipular y controlar objetos con la mente, este es de forma visibles ya que permite transladar los objetos y seres en orbitas de luz. Al igual que la telequinesis cuando es extremadamente poderosa podría controlar incluso átomos individuales."),
("Clarividencia","Es la habilidad de encontrar a cualquier persona, aún sin haberla visto, teniendo como referencia algo de la persona o una foto. Si la otra persona tiene poderes mentales este puede funcionar como una especie de telepatía o visión compartida."),
(" Multiplicación","Consiste en crear ilusiones exactas de uno mismo que al ser golpeadas desaparecen dependiendo del poder que se gaste se pueden crear cientos de copias"),
(" Atracción psíquica","Es la habilidad de hacer que cualquier persona con poderes llegue a donde tú estás sin ella ser consciente de ello."),
(" Encandilamiento","Concepto relativamente nuevo ya que se ha usado muy poco. Esta habilidad hace que cualquier persona se sienta atraída ya sea físicamente o de cualquier otra manera a la persona poseedora del poder. Como por ejemplo intentar hacer que en todo momento esa persona esté contenta como si de un hijo o algún pariente muy estimado se tratara."),
(" Poderes basados en objetos","Poderes que derivan de objetos (también conocidos como artefactos), tales como armadura, joyas, armas y varitas."),
(" Transformadores","Cuando alguien puede transformar las cosas en otras es porque es un transformador"),
(" Transformador material","Puede transformar los materiales en otros"),
(" Transformador de ser","Cuando uno puede transformar en alguien en una criatura, ser vivo, animal, insecto, etc, es un transformador de ser."),
(" Transformación por evolución","Aquellos personajes que se transforman para evolucionar su especie, algunos de ellos evolucionan como etapa de su vida, pero algunos de ellos pueden no decidir cambiar, y prevalecer tal como eran en un principio."),
(" Transformación por nivel de poder","Estos son transformaciones, posiblemente naturales, que otorgan a ciertos personajes para amplificar su poder."),
(" Transformador de material a ser y viceversa","Cuando uno puede transformar materiales a seres con vida, pero de un material biológico o robótico, o cuando puede convertir seres en un material, son denominados transformador de material a ser y viceversa."),
(" Manipulación de poder","Habilidad para manipularlos poderes de otros."),
(" Concesión de poder","Habilidad para conceder poderes a otros o activar poderes en estado latente de otras personas."),
(" Mimetismo o absorción de poder","Habilidad para copiar o absorber poderes o habilidades de otros."),
(" CopyPower","Habilidad de poder copiar (imitar) los poderes que sean usados en contra de uno, quien tiene este poder puede estar cerca de un ser magico o en todo caso alguien con alguna habilidad pero no poder utilizar el poder de quien este cerca hasta que la habilidad sea emitida por el poseedor."),
(" Negación de poder","Habilidad para suprimir o anular los superpoderes o las mutaciones de otros."),
(" Anulación de poder","Habilidad de dañar la red de energia de la victima y poder anular totalmente la capacidad de realizar poderes"),
(" Percepción de poder","Habilidad para sentir y reconocer poderes superhumanos."),
(" Amplificador de poder","Habilidad de recargar y aumentar la potencia de los poderes de otras personas con habilidades, el contacto prolongado puede causar una sobrecarga de poder que puede dañar a una persona hasta matarla."),
(" Intercambio de poder","Habilidad que consiste en intercambiar los poderes de los individuos unos con otros. Quien pose este poder tambien tiene la capacidad de intercambiar sus poderes con otra individuo."),
(" Robo de poder ","Habilidad que permite substraer las habilidades y/o superpoderes de otros seres dejando al individuo sin superpoderes."),
(" Deflexión","Habilidad que consiste en reflejar los poderes que se usan en contra del usuario."),
(" Amnepatía","Habilidad para borrar la mente de las personas. Se puede llegar a borrar de su cabeza cualquier dato personal o simplemente unos instantes de su vida."),
(" Recuperación mental","Habilidad contraria a la amnepatia. Permite al individuo hacer que cualquier persona recupere, desde fragmentos o completamente, la memoria y/o recuerdos previamente borrados."),
(" Poderes de energía","Estos poderes implican la generación, conversión y manipulación de energía. Además de la energía en sentido genérico, distintas versiones de estos poderes involucran fenómenos como la luz, el sonido, la electricidad,la energía nuclear, la fuerza oscura y la energia cosmica."),
(" Manipulación de energía cósmica","La habilidad para manipular y o absorber energia cosmica con diversos propósitos."),
(" Rayos de energía","La habilidad para generar o transformar diversas formas de energía en un rayo de energía 'sólido' destinado a impactar violentamente un objetivo."),
(" Estallidos de energía","Variadas formas de energía que son expelidas violentamente desde el cuerpo."),
(" Constructos de energía","Similares a los campos de fuerza, pero mucho más intrincados, es la habilidad para crear complejas formas (tales como gigantescos guantes de boxeo o jaulas) o incluso maquinaria funcional (como extintores de fuego o rifles láser) hechas de energía solidificada."),
(" Conversión de energía","Convertir una forma de energía en otra, en varias formas e intensidades."),
(" Manipulación de energía","La habilidad de controlar y generar diversas formas de energía."),
(" Campos de fuerza","Escudos de energía, frecuentemente invisibles o translúcidos, producidos como mecanismo de protección."),
(" Elementos clásicos","Habilidad para controlar o manipular los elementos clásicos."),
(" Eoloquinesis o aeroquinesis","Habilidad para controlar, generar o absorber aire o viento."),
(" Crioquinesis","Habilidad para reducir la energía cinética de los átomos y así reducir la temperatura, frecuentemente usada para controlar, generar o absorber hielo."),
(" Geoquinesis","Habilidad para controlar el elemento clásico de la tierra: arena, piedra, roca, lava o polvo,"),
(" Electroquinesis","La electroquinesis es la habilidad de controlar, generar o absorber campos eléctricos. Esto permite a algunos personajes usar la electricidad como forma de ataque."),
(" Piroquinesis","La piroquinesis es la habilidad de generar, controlar o absorber fuego,"),
(" Citoquinesis o cloroquinesis","Habilidad para acelerar el crecimiento, controlar o animar la vida de las plantas."),
(" Hidroquinesis","Habilidad para controlar o como es conosido en la serie Avatar: la leyenda de Aang el Agua-control, generar o absorber agua."),
(" Atmoquinesis","Habilidad para controlar o afectar mentalmente al clima."),
("Sintetización","Capacidad para crear caminos, rocas, montañas, muros, tec"),
(" Manipulación de fuerzas fundamentales de la realidad","Estos poderes pueden manifestarse de varias maneras, tales como: alguna forma de control molecular, un traslado parcial o total hacia otra dimensión, la manipulación de las dimensiones geométricas de tiempo y espacio, o algún otro método no nombrado."),
(" Animación","Poder de dar vida a objetos inanimados o liberar a una persona de un estado de petrificación."),
(" Control de densidad","Habilidad de alterar la densidad de los objetos o incluso de uno mismo. Se manifiesta típicamente de dos formas: intangibilidad (baja densidad) e invulnerabilidad (alta densidad)."),
(" Mimetismo animal","Habilidad para imitar cualquier tipo de acción animal, como por ejemplo el vuelo de un pájaro, la fuerza de grandes animales, la vista de un águila o lince, etc."),
(" Mimetismo muscular","Habilidad para imitar con elevada exactitud movimientos físicos que se hayan visto con anteroridad, sin necesidad de alterar el estado físico o molecular de quien imita la acción. Puede ser desde un salto, una composición musical entera, una llave de artes marciales, una manualidad, etc"),
(" Transmutación elemental o alquimia","Habilidad para alterar los elementos químicos, cambiando una sustancia por otra. Puede estar limitada a la autotransmutación (también conocida como 'alquimia')."),
(" Manipulación de la gravedad","Habilidad para manipular o generar gravitones, u otros tipos de interacciones gravitacionales."),
(" Manipulación de la antimateria","Habilidad para manipular o generar anti-materia, la cual pude ser utilizada para destruir seres o universos hechos de materia positiva"),
(" Inmortalidad","Habilidad que consiste en vivir por siempre. Esto puede ser una inmortalidad completa en la cual el personaje no puede ser matado de ninguna forma, una inmortalidad en la cual el personaje aparentemente muere pero resucita, simplemente una incapacidad para envejecer de forma normal o incluso una inmortalidad condicionada, en que el personaje sólo puede ser eliminado de maneras específicas (por ejemplo, decapitación. También puede darse como consecuencia de otros poderes, como la sanación acelerada"),
(" Fotoquinesis","La fotoquinesis es la habilidad de controlar, generar o absorber fotones partículas de luz"),
(" Magnetoquinesis","La magnetoquinesis es la habilidad de controlar o generar campos magnéticos y controlar metales."),
(" Manipulación de la masa","Habilidad para incrementar o disminuir la masa en un objeto o una persona."),
(" Vibrador molecular","Habilidad que permite al posedor poder hacer que las moléculas vibren por ejemplo: puedes hacer terremotos o maremotos, o bien, poder hacer pasar tus moléculas a través de objetos sólidos."),
(" Manipulación molecular","Habilidad para mentalmente manipular moléculas y objetos a un nivel molecular. Ejemplo clave y especial, es el caso de la bruja Piper Halliwell, la cual puede acelerar las moléculas o desacelerarlas, pudiendo congelar el tiempo o explotar cosas"),
(" Absorción de aura","Habilidad que consiste en ver el Aura de las personas, y absorverla mediante el contacto físico, así como la habilidad que posea esa persona."),
(" Control de aura","Habilidad que consiste en poder usar la propia Aura para potenciarse a si mismo o utilizarla como arma o poder."),
(" Éstasis temporal","El éstasis temporal es la habilidad de desacelerar las moléculas hasta el punto de detenerlas, causando que a lo que sea que se enfoque (ser vivo o no) se congele por un tiempo y sea incapaz de moverse."),
(" Omnipotencia","Habilidad que consiste en la posesión de poderes ilimitados."),
(" Manipulación de la probabilidad","Habilidad para alterar la probabilidad de los eventos, causando que cosas infrecuentes sucedan, o que cosas probables no ocurran. Esto frecuentemente se describe en términos de 'bendiciones' y 'maldiciones'."),
(" Radioquinesis","Habilidad para manipular la radioactividad a través del espectro electromagnético, o generarla desde el propio cuerpo."),
(" Distorsionar la realidad","Habilidad para cambiar o manipular la realidad. Es un forma más avanzada que la Ilusión."),
(" Proyección de pensamiento","Permite volver realidad sus deseos sin el uso de pociones o hechizos."),
(" Proyección de escritura","Consiste en darle vida(hacer realidad) a lo que hemos escrito o en su caso estamos escribiendo."),
(" Sonoquinesis","Audioquinesis, sonoquinesis o ecoquinesis son los distintos nombres que recibe la habilidad de manipular mentalmente las ondas sonoras."),
(" Cronoquinesis","Habilidad para afectar el flujo del tiempo, ralentizándolo, acelerándolo o incluso deteniéndolo."),
(" Hipnoquinesis","Habilidad para controlar los sueños de las personas y poder hacerles ver en su mente lo que se desee. También tiene este control sobre las pesadillas y el poder alterarlas a peor o mejor"),
(" Combustión espontanea","Habilidada de crear de forma inesperada en un objeto y/o persona deseada la aparicion brusca de llamas,las cuales son muy intensas y en un lapso de tiempo muy corto el cuerpo queda completamente destruido y reducido a un pequeño montón de cenizas."),
(" Transportación o viaje","Son habilidades que permiten la transportacion a largas o cortas distancias sin necesidad de un vehículo o el movimiento del cuerpo."),
(" Umbraquinesis","Habilidad para crear o usar la oscuridad, frecuentemente accediendo mentalmente a una dimensión de energía oscura"),
(" Transportación eléctrica","Habilidad para viajar a través de los conductos eléctricos (tales como cables de poder, o líneas telefónicas), frecuentemente entrando a través de dispositivos como televisores, polos eléctricos, tomas de corriente o computadores."),
(" Omnipresencia","Habilidad que consiste en la simultánea presencia en todas partes."),
(" Dimensión de bolsillo","Habilidad para crear dimensiones de bolsillo temporales, o acceder a 'pequeñas' dimensiones permanentes."),
(" Creación de portal","Habilidad para crear agujeros de gusano en el tiempo o el espacio."),
(" Invocación","Habilidad para invocar objetos o seres para la propia asistencia"),
(" Velocidad sobrehumana","Habilidad para moverse más rápido que lo usual. En frecuentes ocasiones, aproximándose a la velocidad de la luz."),
(" Teletransportación","Habilidad para moverse de un lugar a otro sin ocupar espacio o masa en el trayecto."),
(" Orbitación","Habilidad de transportarse mediante luces celestes (partículas volátiles)"),
(" Fluctuar","La capacidad de teletransportarse entre llamas"),
(" Viajar por el tiempo","Habilidad para viajar a través del tiempo."),
(" Poderes físicos personales","Poderes que tienen algún efecto en la constitución física de un individuo."),
(" Sanación acelerada (factor de curación)","Habilidad para curar rápidamente de cualquier lesión. El tiempo de recuperación varía según el personaje, también puede resultar en inmortalidad o al menos en longevidad."),
(" Desarrollo de un álter-ego","Habilidad para desarrollar un álter-ego interior o doble personalidad sea de forma natural o por medio de algo externo (rayos gamma, pociones especiales). Esta segunda personalidad tiene, aparentemente, superfuerza."),
(" Bioquinesis","Habilidad para controlar la vida. Los Manipuladores Biológicos pueden curar, matar, alterar la composición del cuerpo y pueden hacer otras cosas relacionadas con el cuerpo vivo."),
(" Sustitución de partes del cuerpo","Habilidad para reemplazar una propia extremidad u otra parte del cuerpo por la misma extremidad u otra parte diferente. Tambien hacer que la parte del cuerpo se regenere, por ejemplo, que un brazo amputado vuelva a crecer."),
(" Duplicación","Habilidad para crear réplicas (no clones) de uno mismo."),
(" Ecolocación","Habilidad para determinar la ubicación de objetos en el espacio mediante el uso de las reflexiones de las ondas sonoras, sean estas producidas por el sujeto o sonidos ambientales. (También conocida como Sentido Sonar)."),
(" Sentidos aumentados (mejorados)","Aumento de percepción en los sentidos de la vista, el olfato, el gusto, el tacto y la audición."),
(" Invisibilidad","Habilidad para mostrarse u ocultarse al ojo humano normal."),
(" Invulnerabilidad","Inmunidad total o parcial a cualquier clase de daño."),
(" Ingestión de materia","Habilidad para consumir cualquier clase de materia sin que esto provoque malestar o enfermedad en el sujeto."),
(" Armadura natural","Una inusual, resistente y perdurable coraza externa de piel."),
(" Armas naturales","Atributos físicos tales como garras, dientes afilados, púas, redes y otras cualidades usualmente asociadas con animales."),
(" Manipulación de feromonas","La habilidad de generar y controlar las propias feromonas."),
(" Reflejos fotográficos","Habilidad para imitar cualquier acto atlético o movimiento de arte marcial luego de haberlo visto sólo una vez. En otros casos es la habilidadad para esquivar cualquier acto físico con mayor rapidez que la humana."),
(" Envenenar","Habilidad para atacar a otros con una o más variedades de toxinas, con una amplia gama de diversos efectos"),
(" Arma biológica natural/virogénesis","Habilidad que consiste en que la misma persona despida enfermedades, virus, o le cause algún otro tipo de mal a cualquier otro factor biológico, y lo restaure a voluntad o con asistencia."),
(" Adaptación/evolución reactiva","Habilidad para desarrollar una resistencia o inmunidad a cualquier cosa que haya afectado o a la que haya estado expuesto el sujeto."),
(" Autodetonación o explosión","Habilidad de explotar la propia masa corporal y volver a formarla. En otros casos consiste en liberar una gran cantidad de energía del cuerpo"),
(" Separación","Habilidad para separar partes del propio cuerpo y hacer que actúen por su voluntad."),
(" Fusión","Habilidad para fusionarse con otra persona. Esto da como resultado un ser completamente nuevo y más fuerte."),
(" Manipular el cabello","Habilidad que permite utilizar el cabello como una extremidad más del cuerpo, usándolo tanto para atacar y defenderse."),
(" Grito sónico","Habilidad para usar la propia voz de forma ofensiva o defensiva."),
(" Reflejos sobrehumanos","Habilidad para reaccionar más rápido que un humano normal."),
(" Fuerza sobrehumana","Fuerza física por encima de la normal sin necesidad de tener una massa corporal elevada."),
(" Adherencia","Habilidad para aferrarse a objetos o superficies de diversas maneras y movilizarse sobre ellas"),
(" Habilidades animales e insectos","Son hábilidades que se modifican en base a un animal o insecto concreto, como un lobo, un tigre o una araña. Además de ganar sus habilidades también se tienen sus debilidades, o mejor dicho, se adquiere parte del comportamiento del animal o insecto en si"),
(" Longevidad","Capacidad de vivir más de lo normal, este poder puede deverse por provenir de una raza ajena a la humana, por mutaciones o por otros poderes como la sanación acelerada."),
(" Agilidad sobrehumana","Habilidad para moverse con más soltura por un sitio, utilizando brazos y piernas."),
(" Regeneración celular","Este proceso puede darse de forma natural, pero la forma sobrenatural se da en un corto período de tiempo (de forma espontánea) se define como la restauración de tejidos dañados o perdidos, ya sean órganos o extremidades."),
(" Curación","Habilidad que consiste en sanar lesiones fisicas de otros seres vivos atraves del tacto"),
(" Respiracion de vacio","Habilidad para respirar en cualquier ambiente, pero este no es inmune a cualquier tipo de agente toxico."),
(" Petrificacion","Es la habilidada de transformar cualquier cosa en piedra, esta puede ser emitida por la vista ,tacto,saliva o alguna otra forma que se les ocurra."),
(" Inmunidad","Esta habilidad consiste en no poder ser dañado por cualquiera que sea la habilidad utilizada contra uno. "),
(" Omnilingüismo","Habilidad para descifrar cualquier lenguaje."),
(" Omnisciencia","Capacidad de saberlo todo."),
(" Inteligencia sobrehumana","Inteligencia muy por encima del nivel de genio, frecuentemente acompañada por la habilidad de inventar increíble y avanzada tecnología, la super inteligencia puede deberse a un proceso natural ganado por el esfuerzo de la persona o por exposición a radiación o químicos que causan un extraño desarrollo cerebral"),
(" Memoria sobrehumana","Capacidad para no olvidar ningún escrito, imagen, sonido, etc., asumidos anteriormente. También puede llamársele Mnemonismo. La diferencia entre la 1era es que se puede recordar todo lo percibido a voluntad, el mnemonismo no permite olvidar y no muestra un control sobre la memoria."),
(" Memoria Recreativa","Capacidad para poder Manipular cualquier Recuerdo almacenado. pueden ser escritos, imágenes, sonidos incluso en concentraciones mayores manipular el tacto y los sentidos (vista, gusto, tacto, olfato y audición)."),
(" Actitud intuitiva","Habilidad que permite conocer de forma precoz, el funcionamiento de sistemas complejos y poder usarlos o manipularlos."),
(" Percepción extrasensorial (PES)","Las habilidades de percepción y comunicación extrasensorial."),
(" Proyección astral","Habilidad para separar y controlar el propio cuerpo astral, este puede ser translucido o corporal.Normalmente el cuerpo astral no puede usar los poderes del cuerpo inconsciente, pero cuando se congue practica si se puede e incluso pueden proyectarse con el cuerpo consciente."),
(" Clarividencia y clariaudiencia","Clarividencia es la habilidad para percibir eventos que están ocurriendo en otro lugar o sentir lugares que no están a la vista como si se estuviera presente. Frecuentemente permite ver sucesos futuros. La clariaudiencia es la habilidad auditiva equivalente a la clarividencia, permitiendo escuchar como si se estuviera en ese lugar. Otros sentidos remotos también pueden manifestarse de esta forma."),
(" Conocimiento más allá de la propia dimensión","Habilidad para detectar y tomar conocimiento de acciones y eventos en otras dimensiones. Esto ocasionalmente es utilizado en comics como la toma de consciencia de la existencia del 'cuarto muro' (un muro imaginario que separa el mundo de ficción del real) entre los personajes y el guionista o dibujante, o incluso, entre los personajes y los lectores."),
(" Sentido del peligro","Habilidad para percibir el peligro personal. Es una forma limitada de precognicion."),
(" Empatía","Habilidad para leer o sentir las emociones y sentimientos de otros. En algunos casos, los empáticos que desarrollan esta habilidad pueden proyectar su empatía a otros, haciendo así que estos compartan sus emociones."),
(" Precognición/premonición","Habilidad para percibir el futuro. En ocasiones solamente se expresa en la forma de vagos sueños mientras se duerme, mientras que otras veces es clara y ocurre a voluntad, mientras se está despierto, o incluso pintándolo."),
(" Psicometría","Habilidad para relatar detalles sobre la condición pasada o futura de un objeto, persona o locación, usualmente estando en contacto cercano a él/ella, o directamente mediante contacto físico."),
("Telepatía","Habilidad para comunicarse mentalmente con otros, rompiendo las barreras de la distancia. Generalmente, permite hablar en un lenguaje universal. Si el grado de dominio es alto, tambien puede canalizar los poderes y usarlos."),
("Asentamiento astral","Habilidad para crear una proyección astral para quedarse en el plano astral, usualmente en un lugar específico."),
("Control mental","Poder para controlar las acciones o el razonamiento de otra persona."),
("Posesión","Habilidad para tomar control del cuerpo de otras personas mediante la proyección astral, la transferencia de mente o transformar el cuerpo físico en un estado fantasmal y entrar en el cuerpo de otra persona. Una forma especializada de Control Mental."),
("Persuasión","Capacidad de hacer que otras personas realicen acciones, sin que éstas puedan negarse, mediante palabras con entonación imperativa, es decir, ordenándolas."),
("Estallido psiónico","Habilidad para sobrecargar una mente ajena, luego de haber establecido un vínculo psiónico con la mente de esa persona, causando dolor, pérdida de memoria, inconsciencia, estado vegetativo o incluso la muerte."),
("Armas psíquicas","Habilidad para crear un arma, como un cuchillo o una granada, hecha de energía psiónica que puede dañar mentalmente y no físicamente."),
("Visión Rayos X","Puede ver atrás de las murallas, una persona común ve la muralla, pero con este poder, puede ver lo que esta pasando detrás de las cosas o dentro de ellas."),
("Visión láser","Permite disparar laser sin ser dañado através de los ojos. Esto se puede controlar o no dependiendo el tipo de visión de láser que le toque."),
("Visión telequinética","Uno de los poderes que pocas veces apareció, y que no se usó más debido posiblemente por su poca aceptabilidad. "),
("Visión Compartida y Visión Remota","Es la habilidad de poder ver atraves de los ojos de los demas o en otros casos, hacer que los demas puedan ver lo que estamos viendo en ese momento."),
("Visión nocturna","Es la habilidada de poder ver en la oscuridad en los entornos que están en bajos niveles de iluminación."),
("Visión Termica","Es la habilidada de poder ver la temperatura de un cuerpo."),
("Visión contaminable","Es como la visión láser, solo que dispara através de sus ojos la contaminación."),
("Volar ","Habilidad para alzarse desde el suelo, para navegar las corrientes de aire o volar por propia cuenta a través del aire. Las diferentes formas de volar incluyen:"),
("Ilusión","Habilidad para alterar o engañar las percepciones de otra persona. Usualmente visual, puede ser un efecto basado en la luz, basado en el sonido, un efecto producido al afectar la mente ajena, o cualquier otro efecto que cause el percibir cosas que no necesariamente son reales."),
("Polimorfismo","Habilidad para cambiar la apariencia o la estructura corporal temporalmente, así como alterar la de otros seres."),
("Mimetismo virtual","Aquellos movimientos basados y obtenidos de cosas más ficticias, son un mimetismo virtual."),
("Manipulación de la gravedad","Capacidad y habilidad, de controlar la gravedad sobre las cosas y sobre el mismo, sobre todo."),
("Habilidad o poder para hacer fuegos pirotécnicos","Es capaz de hacer estos fuegos Pirotécnicos apesar de que no sean mediante forma artificial."),
("Suerte exagerada","Algunos personajes tienen tanta suerte, que siempre les irá perfecto, o batirán cualquier cosa, conseguirán lo que quieren, y siempre los van a querer demasiado, si así lo desean."),
("Sinestesia","Poder de sentir las mismas emociones de un sentido en otros sentidos diferentes"),
("Aliento de fuego","Capacidad de formar fuego por los gases o el aliento desde su boca."),
("Aliento de hielo","Le dicen así por que hace congelar las cosas y no por que dispare hielo por la boca. Es como el aliento de fuego, solo que para enfriar."),
("Aliento tóxico","Capacidad de formar tóxinas através del aliento de su boca. En algunos villanos como en uno de Ben 10, podía exparcir algo tóxico que derretía materiales."),
("Súper aliento","Habilidad de que, al soplar, el soplido sea como un ventarrón de aire, llegando a impulsar objetos pesados a largas distancias."),
("Poderes definidos","Ciertos super poderes que son un conjunto de poderes ya mencionados. Estos podrían ser un poder en si que otorga ciertas habilidades de otros super poderes, o en este caso también podría ser solo un conjunto de super poderes."),
("Magia","Estos es un poder misterioso que no tiene explicación, esto puede ser divino, o místico, algo que podría derivar en una fuerza o habilidad sobrenatural."),
("Manipulación del espacio-tiempo","Aquí se entiende espacio y tiempo como una sola cosa, esto debido a que el espacio y el tiempo estan determinados para conformar la realidad, en este caso, se puede manipular la realidad, por estas dos bases, pero debido a que no podemos crear una realidad diferente con solo pensarlo, se le es considerado de espacio-tiempo.Los poderes que se tiene"),
("El poder del absurdo","Este poder no esta definido, pero sería el hecho de poder crear o realizar cosas absurdas aún cuando evaden la lógica de la realidad."),
("Caricaturismo","Capacidad de actuar y hacer cosas como una caricatura de fantasía.");

INSERT INTO t_condicion (connom) VALUES ('Preso'), ('Libre'), ('Desconocida');

INSERT INTO t_pais (paicod, painom) VALUES ("AD", "Andorra" ),
("AE", "Emiratos Árabes Unidos" ),
("AF", "Afganistán" ),
("AG", "Antigua y Barbuda" ),
("AI", "Anguila" ),
("AL", "Albania" ),
("AM", "Armenia" ),
("AN", "Antillas Neerlandesas" ),
("AO", "Angola" ),
("AQ", "Antártida" ),
("AR", "Argentina" ),
("AS", "Samoa Americana" ),
("AT", "Austria" ),
("AU", "Australia" ),
("AW", "Aruba" ),
("AX", "Islas Áland" ),
("AZ", "Azerbaiyán" ),
("BA", "Bosnia y Herzegovina" ),
("BB", "Barbados" ),
("BD", "Bangladesh" ),
("BE", "Bélgica" ),
("BF", "Burkina Faso" ),
("BG", "Bulgaria" ),
("BH", "Bahréin" ),
("BI", "Burundi" ),
("BJ", "Benin" ),
("BL", "San Bartolomé" ),
("BM", "Bermudas" ),
("BN", "Brunéi" ),
("BO", "Bolivia" ),
("BR", "Brasil" ),
("BS", "Bahamas" ),
("BT", "Bhután" ),
("BV", "Isla Bouvet" ),
("BW", "Botsuana" ),
("BY", "Belarús" ),
("BZ", "Belice" ),
("CA", "Canadá" ),
("CC", "Islas Cocos" ),
("CF", "República Centro-Africana" ),
("CG", "Congo" ),
("CH", "Suiza" ),
("CI", "Costa de Marfil" ),
("CK", "Islas Cook" ),
("CL", "Chile" ),
("CM", "Camerún" ),
("CN", "China" ),
("CO", "Colombia" ),
("CR", "Costa Rica" ),
("CU", "Cuba" ),
("CV", "Cabo Verde" ),
("CX", "Islas Christmas" ),
("CY", "Chipre" ),
("CZ", "República Checa" ),
("DE", "Alemania" ),
("DJ", "Yibuti" ),
("DK", "Dinamarca" ),
("DM", "Domínica" ),
("DO", "República Dominicana" ),
("DZ", "Argel" ),
("EC", "Ecuador" ),
("EE", "Estonia" ),
("EG", "Egipto" ),
("EH", "Sahara Occidental" ),
("ER", "Eritrea" ),
("ES", "España" ),
("ET", "Etiopía" ),
("FI", "Finlandia" ),
("FJ", "Fiji" ),
("FK", "Islas Malvinas" ),
("FM", "Micronesia" ),
("FO", "Islas Faroe" ),
("FR", "Francia" ),
("GA", "Gabón" ),
("GB", "Reino Unido" ),
("GD", "Granada" ),
("GE", "Georgia" ),
("GF", "Guayana Francesa" ),
("GG", "Guernsey" ),
("GH", "Ghana" ),
("GI", "Gibraltar" ),
("GL", "Groenlandia" ),
("GM", "Gambia" ),
("GN", "Guinea" ),
("GP", "Guadalupe" ),
("GQ", "Guinea Ecuatorial" ),
("GR", "Grecia" ),
("GS", "Georgia del Sur e Islas Sandwich del Sur" ),
("GT", "Guatemala" ),
("GU", "Guam" ),
("GW", "Guinea-Bissau" ),
("GY", "Guayana" ),
("HK", "Hong Kong" ),
("HM", "Islas Heard y McDonald" ),
("HN", "Honduras" ),
("HR", "Croacia" ),
("HT", "Haití" ),
("HU", "Hungría" ),
("ID", "Indonesia" ),
("IE", "Irlanda" ),
("IL", "Israel" ),
("IM", "Isla de Man" ),
("IN", "India" ),
("IO", "Territorio Británico del Océano Índico" ),
("IQ", "Irak" ),
("IR", "Irán" ),
("IS", "Islandia" ),
("IT", "Italia" ),
("JE", "Jersey" ),
("JM", "Jamaica" ),
("JO", "Jordania" ),
("JP", "Japón" ),
("KE", "Kenia" ),
("KG", "Kirguistán" ),
("KH", "Camboya" ),
("KI", "Kiribati" ),
("KM", "Comoros" ),
("KN", "San Cristóbal y Nieves" ),
("KP", "Corea del Norte" ),
("KR", "Corea del Sur" ),
("KW", "Kuwait" ),
("KY", "Islas Caimán" ),
("KZ", "Kazajstán" ),
("LA", "Laos" ),
("LB", "Líbano" ),
("LC", "Santa Lucía" ),
("LI", "Liechtenstein" ),
("LK", "Sri Lanka" ),
("LR", "Liberia" ),
("LS", "Lesotho" ),
("LT", "Lituania" ),
("LU", "Luxemburgo" ),
("LV", "Letonia" ),
("LY", "Libia" ),
("MA", "Marruecos" ),
("MC", "Mónaco" ),
("MD", "Moldova" ),
("ME", "Montenegro" ),
("MG", "Madagascar" ),
("MH", "Islas Marshall" ),
("MK", "Macedonia" ),
("ML", "Mali" ),
("MM", "Myanmar" ),
("MN", "Mongolia" ),
("MO", "Macao" ),
("MQ", "Martinica" ),
("MR", "Mauritania" ),
("MS", "Montserrat" ),
("MT", "Malta" ),
("MU", "Mauricio" ),
("MV", "Maldivas" ),
("MW", "Malawi" ),
("MX", "México" ),
("MY", "Malasia" ),
("MZ", "Mozambique" ),
("NA", "Namibia" ),
("NC", "Nueva Caledonia" ),
("NE", "Níger" ),
("NF", "Islas Norkfolk" ),
("NG", "Nigeria" ),
("NI", "Nicaragua" ),
("NL", "Países Bajos" ),
("NO", "Noruega" ),
("NP", "Nepal" ),
("NR", "Nauru" ),
("NU", "Niue" ),
("NZ", "Nueva Zelanda" ),
("OM", "Omán" ),
("PA", "Panamá" ),
("PE", "Perú" ),
("PF", "Polinesia Francesa" ),
("PG", "Papúa Nueva Guinea" ),
("PH", "Filipinas" ),
("PK", "Pakistán" ),
("PL", "Polonia" ),
("PM", "San Pedro y Miquelón" ),
("PN", "Islas Pitcairn" ),
("PR", "Puerto Rico" ),
("PS", "Palestina" ),
("PT", "Portugal" ),
("PW", "Islas Palaos" ),
("PY", "Paraguay" ),
("QA", "Qatar" ),
("RE", "Reunión" ),
("RO", "Rumanía" ),
("RS", "Serbia y Montenegro" ),
("RU", "Rusia" ),
("RW", "Ruanda" ),
("SA", "Arabia Saudita" ),
("SB", "Islas Solomón" ),
("SC", "Seychelles" ),
("SD", "Sudán" ),
("SE", "Suecia" ),
("SG", "Singapur" ),
("SH", "Santa Elena" ),
("SI", "Eslovenia" ),
("SJ", "Islas Svalbard y Jan Mayen" ),
("SK", "Eslovaquia" ),
("SL", "Sierra Leona" ),
("SM", "San Marino" ),
("SN", "Senegal" ),
("SO", "Somalia" ),
("SR", "Surinam" ),
("ST", "Santo Tomé y Príncipe" ),
("SV", "El Salvador" ),
("SY", "Siria" ),
("SZ", "Suazilandia" ),
("TC", "Islas Turcas y Caicos" ),
("TD", "Chad" ),
("TF", "Territorios Australes Franceses" ),
("TG", "Togo" ),
("TH", "Tailandia" ),
("TH", "Tanzania" ),
("TJ", "Tayikistán" ),
("TK", "Tokelau" ),
("TL", "Timor-Leste" ),
("TM", "Turkmenistán" ),
("TN", "Túnez" ),
("TO", "Tonga" ),
("TR", "Turquía" ),
("TT", "Trinidad y Tobago" ),
("TV", "Tuvalu" ),
("TW", "Taiwán" ),
("UA", "Ucrania" ),
("UG", "Uganda" ),
("US", "Estados Unidos de América" ),
("UY", "Uruguay" ),
("UZ", "Uzbekistán" ),
("VA", "Ciudad del Vaticano" ),
("VC", "San Vicente y las Granadinas" ),
("VE", "Venezuela" ),
("VG", "Islas Vírgenes Británicas" ),
("VI", "Islas Vírgenes de los Estados Unidos de América" ),
("VN", "Vietnam" ),
("VU", "Vanuatu" ),
("WF", "Wallis y Futuna" ),
("WS", "Samoa" ),
("YE", "Yemen" ),
("YT", "Mayotte" ),
("ZA", "Sudáfrica" ),
('FC', 'Ficticio');


INSERT INTO t_rol (rolafinidad) VALUES ('Heroe'),
('Villano'),
('Antiheroe'),
('Sin motivaciones'),
('Indeterminado');


INSERT INTO t_vehiculo (vehnom, vehdescripcion, vehcodigo) VALUES ('Silla de ruedas', 'El usuario define la dirección con la meditación. Si uno empieza a relajar los músculos y respirar profundamente, se entra en un estado de meditación. Y cuando suben los niveles de concentración, empieza a avanzar la silla', 'VCH'),
('X-Jet', 'es un avión ficticio que aparece en los cómics estadounidenses publicados por Marvel Comics. El avión está representado por el equipo de superhéroes X-Men. Ha habido varias encarnaciones de esta nave a lo largo de los años, con Cíclope y Tormenta como los principales pilotos.', 'XJT'),
('BLITZ BUGGY', 'Podemos ver a Namor a bordo de un jeep que el mismo construyo', 'VCH'),
('Ninguno', 'No usa vehiculo', 'NOT'),
('Motocicleta', 'Vehiculo a motor de dos ruedas', 'MOT');

INSERT INTO t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES
("Warren Kenneth Worthington III",1,"Ángel ",4,4,2,226,5,"https://static.wikia.nocookie.net/xmenmovies/images/1/15/AngelFP.jpg/revision/latest/scale-to-width-down/350?cb=20160422202636"),
("Wanda Maximoff",1,"Bruja Escarlata",5,4,2,226,6,"https://media.vandalsports.com/i/1706x960/7-2022/202271815330_1.jpg.webp"),
("Charles Francis Xavier",1,"Charles Xavier",1,1,2,75,8,"https://images.hindustantimes.com/img/2022/03/25/400x225/X-Men-Apocalypse-James-McAvoy_1648208390595_1648208403795.jpg"),
("Scott Summers",1,"Cíclope",1,2,2,226,9,"https://i0.wp.com/wipy.tv/wp-content/uploads/2021/06/el-mcu-no-esta-honrando-a-hulk-1.jpeg?resize=768%2C461&ssl=1"),
("Piotr Peter Nikolaievitch Rasputin",1,"Coloso ",1,2,2,187,7,"https://dam.smashmexico.com.mx/wp-content/uploads/2020/03/deadpool-coloso-768x512.jpg"),
("Remy Etienne LeBeau",1,"Gambito ",1,2,2,73,6,"https://sm.ign.com/t/ign_es/feature/g/gambit-exp/gambit-explained-who-is-the-x-men-character_1nw3.1280.jpg"),
("Robert Louis Bobby Drake",1,"Iceman ",1,4,2,226,1,"https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Iceman.png/220px-Iceman.png"),
("Jean Elaine Grey Summers",1,"Jean Grey",3,2,2,226,7,"https://static.wikia.nocookie.net/marveldatabase/images/4/4d/A.X.E._Judgment_Day_Vol_1_3_Women_of_A.X.E._Variant_Textless.jpg/revision/latest/scale-to-width-down/323?cb=20220711112817"),
("Jubilation Lee",1,"Júbilo",4,2,2,226,9,"https://i0.wp.com/codigoespagueti.com/wp-content/uploads/2021/12/My-Hero-Academia-Himiko-Toga-te-dejara-sin-palabras-con-este-bellisimo-cosplay-body-paint-7.jpg?resize=1280%2C720&quality=80&ssl=1"),
("Alyosha Kravinoff",1,"Kraven el Cazador",5,4,2,240,5,"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/kraven-cazador-peliculas-spider-man-1539178191.jpg?crop=1.00xw:0.892xh,0,0&resize=768:*"),
("Erik Lehnsherr",1,"Magneto",2,4,2,55,8,"https://static.wikia.nocookie.net/universo-cinematografico-de-xmen/images/5/5c/Magneto1.jpg/revision/latest/scale-to-width-down/333?cb=20160901214220&path-prefix=es"),
("Dr. Nathaniel Essex",1,"Mr. Siniestro",2,4,2,226,3,"https://dam.smashmexico.com.mx/wp-content/uploads/2020/05/mr-sinister-villano-pelicula-gambit-cancelada-cover-768x512.jpg"),
("Raven Darkhölme",1,"Mystique",2,4,2,226,2,"https://assets.mycast.io/characters/mistique-3660315-normal.jpg?1632203682"),
("Namor McKenzie",1,"Namor",3,3,2,226,6,"https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/NAMOR1cover-CMYKcrop.jpg/220px-NAMOR1cover-CMYKcrop.jpg"),
("Ellie Phimister",1,"Negasonic Teenage Warhead",1,2,2,226,8,"https://i.ytimg.com/vi/tgg4y9_rk4E/hqdefault.jpg"),
("Kurt Szards",1,"Nightcrawler",3,4,2,55,9,"https://static.wikia.nocookie.net/xmen9260/images/0/0d/X2nightcrawl.jpg/revision/latest/scale-to-width-down/350?cb=20190717172237&path-prefix=es"),
("St. John Allerdyce",1,"Pyro",5,5,2,14,3,"https://static.wikia.nocookie.net/xmenmovies/images/e/ef/Pyro_%28X-Men-_The_Last_Stand%29.jpg/revision/latest/scale-to-width-down/350?cb=20150611182241"),
("Pietro Maximoff",1,"Quicksilver",1,4,2,226,2,"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2020/06/hipertextual-evan-peters-quicksilver-x-men-apareceria-wandavision-2020612247.jpg?resize=700%2C448&quality=60&strip=all&ssl=1"),
("Víctor Creed",1,"Sabretooth",2,4,2,226,1,"https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Sabretooth_%28Victor_Creed%29.jpg/220px-Sabretooth_%28Victor_Creed%29.jpg"),
("James Howlett/Logan",1,"Wolverine",3,2,2,226,7,"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/02/hipertextual-disney-busqueda-nuevo-wolverine-integrarlo-universo-cinematografico-marvel-2019958269-scaled.jpg?w=1560&quality=60&strip=all&ssl=1");


UPDATE t_mutantes SET `mutimg` = 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/styles/hc_1440x810/public/media/image/2019/03/magneto.jpg?itok=u3-bZu95' WHERE (`mutid` = '11'),
UPDATE t_mutantes SET `mutimg` = 'https://bbts1.azureedge.net/images/p/full/2020/12/76b0440b-4874-4880-b602-77a2f123ce5d.jpg' WHERE (`mutid` = '16'),
UPDATE t_mutantes SET `mutimg` = 'http://pm1.narvii.com/6579/a898ffbeb6937693b468bf940ce13d5bfe3b4677_00.jpg' WHERE (`mutid` = '1'),
UPDATE t_mutantes SET `mutimg` = 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/05/Pyro-contemplates-the-flame.jpg?q=50&fit=crop&w=750&dpr=1.5' WHERE (`mutid` = '17'),

INSERT INTO t_poder_mutante (podid, mutid) VALUES 
('1', '2'),
('1', '11'),
('1', '12'),
('1', '13'),
('2', '14'),
('2', '15'),
('2', '16'),
('2', '17'),
('3', '18'),
('3', '19'),
('4', '20'),
('4', '21'),
('5', '22'),
('5', '23'),
('6', '24'),
('7', '26'),
('8', '27'),
('9', '28'),
('9', '29'),
('10', '30'),
('11', '31'),
('11', '32'),
('12', '33'),
('12', '34'),
('13', '36'),
('14', '37'),
('14', '38'),
('14', '39'),
('14', '40'),
('15', '41'),
('16', '42'),
('17', '101'),
('17', '102'),
('17', '103'),
('18', '105'),
('18', '106'),
('19', '107'),
('19', '102'),
('20', '108'),
('20', '109');


UPDATE t_vehiculo SET vehimg = 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/styles/hc_1440x810/public/media/image/2013/02/210781-bryan-singer-muestra-sillas-profesor-xavier.jpg?itok=65FdMpNR' WHERE (`vehid` = '1');
UPDATE t_vehiculo SET vehdescripcion = 'El \"Blitz-Buggy\" podría alcanzar velocidades superiores a las de los jeeps militares que se construyeron en la década de 1940 (el vehículo militar blindado estadounidense promedio de ese tamaño alcanza velocidades máximas entre 40 y 56 MPH), cuyo rango superior se desconoce.', `vehimg` = 'https://static.wikia.nocookie.net/marveldatabase/images/8/8c/Namor%27s_Jeep_from_Marvel_Mystery_Comics_Vol_1_22_0001.jpg/revision/latest?cb=20110501194746' WHERE (`vehid` = '3'),
UPDATE t_vehiculo SET vehdescripcion = 'Vehiculo a motor de dos ruedas.' WHERE (`vehid` = '5'),
UPDATE t_vehiculo SET vehdescripcion = 'No usa vehiculo,(N/A)', `vehimg` = 'https://supercurioso.com/wp-content/uploads/2016/01/supervelocidad.jpg' WHERE (`vehid` = '4'),
UPDATE t_vehiculo SET vehimg = 'https://cmro.travis-starnes.com/images/equipment/blitz-buggy.jpg' WHERE (`vehid` = '3'),