INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Aspecto físico no-humano","El poder puede provenir de un rasgo no-humano de la constitución física del sujeto (una criatura completamente formada por fuego, o roca, por ejemplo).");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Tecnopatía","Habilidad para manipular tecnología. Puede manifestarse como una forma particular de manipulación eléctrica, una forma especial de polimorfismo, o incluso una forma especial de percepción extrasensorial.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Tecnoquinesis","Habilidad para construir o formar máquinas através de un material. Esto se ha visto en películas como Escuela de Súper Héroes, donde la villana podía con un bloque de metal, crear una arma letal o en X-Men donde una persona transforma su brazo en una máquina de reparación");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Ciberpatía","Habilidad para conectarse a Internet inalambricamente, mandar mensajes e infectar con virus a las computadoras, todo desde la mente. Hay mayor recepción cuando se encuentra en lugares libres y a gran altura.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Telequinesis","Habilidad para manipular y controlar objetos con la mente, frecuentemente de forma no visibles para el ojo humano normal. Una telequinesis extremadamente poderosa podría controlar incluso átomos individuales.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Telequinesis orbitacional","Habilidad para manipular y controlar objetos con la mente, este es de forma visibles ya que permite transladar los objetos y seres en orbitas de luz. Al igual que la telequinesis cuando es extremadamente poderosa podría controlar incluso átomos individuales.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Clarividencia","Es la habilidad de encontrar a cualquier persona, aún sin haberla visto, teniendo como referencia algo de la persona o una foto. Si la otra persona tiene poderes mentales este puede funcionar como una especie de telepatía o visión compartida.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Multiplicación","Consiste en crear ilusiones exactas de uno mismo que al ser golpeadas desaparecen dependiendo del poder que se gaste se pueden crear cientos de copias");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Atracción psíquica","Es la habilidad de hacer que cualquier persona con poderes llegue a donde tú estás sin ella ser consciente de ello.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Encandilamiento","Concepto relativamente nuevo ya que se ha usado muy poco. Esta habilidad hace que cualquier persona se sienta atraída ya sea físicamente o de cualquier otra manera a la persona poseedora del poder. Como por ejemplo intentar hacer que en todo momento esa persona esté contenta como si de un hijo o algún pariente muy estimado se tratara.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Poderes basados en objetos","Poderes que derivan de objetos (también conocidos como artefactos), tales como armadura, joyas, armas y varitas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transformadores","Cuando alguien puede transformar las cosas en otras es porque es un transformador");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transformador material","Puede transformar los materiales en otros");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transformador de ser","Cuando uno puede transformar en alguien en una criatura, ser vivo, animal, insecto, etc, es un transformador de ser.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transformación por evolución","Aquellos personajes que se transforman para evolucionar su especie, algunos de ellos evolucionan como etapa de su vida, pero algunos de ellos pueden no decidir cambiar, y prevalecer tal como eran en un principio.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transformación por nivel de poder","Estos son transformaciones, posiblemente naturales, que otorgan a ciertos personajes para amplificar su poder.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transformador de material a ser y viceversa","Cuando uno puede transformar materiales a seres con vida, pero de un material biológico o robótico, o cuando puede convertir seres en un material, son denominados transformador de material a ser y viceversa.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de poder","Habilidad para manipularlos poderes de otros.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Concesión de poder","Habilidad para conceder poderes a otros o activar poderes en estado latente de otras personas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Mimetismo o absorción de poder","Habilidad para copiar o absorber poderes o habilidades de otros.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" CopyPower","Habilidad de poder copiar (imitar) los poderes que sean usados en contra de uno; quien tiene este poder puede estar cerca de un ser magico o en todo caso alguien con alguna habilidad pero no poder utilizar el poder de quien este cerca hasta que la habilidad sea emitida por el poseedor.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Negación de poder","Habilidad para suprimir o anular los superpoderes o las mutaciones de otros.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Anulación de poder","Habilidad de dañar la red de energia de la victima y poder anular totalmente la capacidad de realizar poderes");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Percepción de poder","Habilidad para sentir y reconocer poderes superhumanos.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Amplificador de poder","Habilidad de recargar y aumentar la potencia de los poderes de otras personas con habilidades, el contacto prolongado puede causar una sobrecarga de poder que puede dañar a una persona hasta matarla.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Intercambio de poder","Habilidad que consiste en intercambiar los poderes de los individuos unos con otros. Quien pose este poder tambien tiene la capacidad de intercambiar sus poderes con otra individuo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Robo de poder ","Habilidad que permite substraer las habilidades y/o superpoderes de otros seres dejando al individuo sin superpoderes.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Deflexión","Habilidad que consiste en reflejar los poderes que se usan en contra del usuario.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Amnepatía","Habilidad para borrar la mente de las personas. Se puede llegar a borrar de su cabeza cualquier dato personal o simplemente unos instantes de su vida.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Recuperación mental","Habilidad contraria a la amnepatia. Permite al individuo hacer que cualquier persona recupere, desde fragmentos o completamente, la memoria y/o recuerdos previamente borrados.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Poderes de energía","Estos poderes implican la generación, conversión y manipulación de energía. Además de la energía en sentido genérico, distintas versiones de estos poderes involucran fenómenos como la luz, el sonido, la electricidad,la energía nuclear, la fuerza oscura y la energia cosmica.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de energía cósmica","La habilidad para manipular y o absorber energia cosmica con diversos propósitos.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Rayos de energía","La habilidad para generar o transformar diversas formas de energía en un rayo de energía “sólido” destinado a impactar violentamente un objetivo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Estallidos de energía","Variadas formas de energía que son expelidas violentamente desde el cuerpo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Constructos de energía","Similares a los campos de fuerza, pero mucho más intrincados; es la habilidad para crear complejas formas (tales como gigantescos guantes de boxeo o jaulas) o incluso maquinaria funcional (como extintores de fuego o rifles láser) hechas de energía solidificada.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Conversión de energía","Convertir una forma de energía en otra, en varias formas e intensidades.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de energía","La habilidad de controlar y generar diversas formas de energía.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Campos de fuerza","Escudos de energía, frecuentemente invisibles o translúcidos, producidos como mecanismo de protección.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Elementos clásicos","Habilidad para controlar o manipular los elementos clásicos.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Eoloquinesis o aeroquinesis","Habilidad para controlar, generar o absorber aire o viento.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Crioquinesis","Habilidad para reducir la energía cinética de los átomos y así reducir la temperatura, frecuentemente usada para controlar, generar o absorber hielo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Geoquinesis","Habilidad para controlar el elemento clásico de la tierra: arena, piedra, roca, lava o polvo;");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Electroquinesis","La electroquinesis es la habilidad de controlar, generar o absorber campos eléctricos. Esto permite a algunos personajes usar la electricidad como forma de ataque.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Piroquinesis","La piroquinesis es la habilidad de generar, controlar o absorber fuego,");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Citoquinesis o cloroquinesis","Habilidad para acelerar el crecimiento, controlar o animar la vida de las plantas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Hidroquinesis","Habilidad para controlar o como es conosido en la serie Avatar: la leyenda de Aang el Agua-control, generar o absorber agua.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Atmoquinesis","Habilidad para controlar o afectar mentalmente al clima.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Sintetización","Capacidad para crear caminos, rocas, montañas, muros, tec");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de fuerzas fundamentales de la realidad","Estos poderes pueden manifestarse de varias maneras, tales como: alguna forma de control molecular, un traslado parcial o total hacia otra dimensión, la manipulación de las dimensiones geométricas de tiempo y espacio, o algún otro método no nombrado.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Animación","Poder de dar vida a objetos inanimados o liberar a una persona de un estado de petrificación.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Control de densidad","Habilidad de alterar la densidad de los objetos o incluso de uno mismo. Se manifiesta típicamente de dos formas: intangibilidad (baja densidad) e invulnerabilidad (alta densidad).");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Mimetismo animal","Habilidad para imitar cualquier tipo de acción animal, como por ejemplo el vuelo de un pájaro, la fuerza de grandes animales, la vista de un águila o lince, etc.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Mimetismo muscular","Habilidad para imitar con elevada exactitud movimientos físicos que se hayan visto con anteroridad, sin necesidad de alterar el estado físico o molecular de quien imita la acción. Puede ser desde un salto, una composición musical entera, una llave de artes marciales, una manualidad, etc");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transmutación elemental o alquimia","Habilidad para alterar los elementos químicos, cambiando una sustancia por otra. Puede estar limitada a la autotransmutación (también conocida como “alquimia”).");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de la gravedad","Habilidad para manipular o generar gravitones, u otros tipos de interacciones gravitacionales.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de la antimateria","Habilidad para manipular o generar anti-materia, la cual pude ser utilizada para destruir seres o universos hechos de materia positiva");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Inmortalidad","Habilidad que consiste en vivir por siempre. Esto puede ser una inmortalidad completa en la cual el personaje no puede ser matado de ninguna forma, una inmortalidad en la cual el personaje aparentemente muere pero resucita, simplemente una incapacidad para envejecer de forma normal o incluso una inmortalidad condicionada, en que el personaje sólo puede ser eliminado de maneras específicas (por ejemplo, decapitación. También puede darse como consecuencia de otros poderes, como la sanación acelerada");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Fotoquinesis","La fotoquinesis es la habilidad de controlar, generar o absorber fotones (partículas de luz)");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Magnetoquinesis","La magnetoquinesis es la habilidad de controlar o generar campos magnéticos y controlar metales.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de la masa","Habilidad para incrementar o disminuir la masa en un objeto o una persona.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Vibrador molecular","Habilidad que permite al posedor poder hacer que las moléculas vibren por ejemplo: puedes hacer terremotos o maremotos, o bien, poder hacer pasar tus moléculas a través de objetos sólidos.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación molecular","Habilidad para mentalmente manipular moléculas y objetos a un nivel molecular. Ejemplo clave y especial, es el caso de la bruja Piper Halliwell, la cual puede acelerar las moléculas o desacelerarlas, pudiendo congelar el tiempo o explotar cosas");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Absorción de aura","Habilidad que consiste en ver el Aura de las personas, y absorverla mediante el contacto físico, así como la habilidad que posea esa persona.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Control de aura","Habilidad que consiste en poder usar la propia Aura para potenciarse a si mismo o utilizarla como arma o poder.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Éstasis temporal","El éstasis temporal es la habilidad de desacelerar las moléculas hasta el punto de detenerlas, causando que a lo que sea que se enfoque (ser vivo o no) se congele por un tiempo y sea incapaz de moverse.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Omnipotencia","Habilidad que consiste en la posesión de poderes ilimitados.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de la probabilidad","Habilidad para alterar la probabilidad de los eventos, causando que cosas infrecuentes sucedan, o que cosas probables no ocurran. Esto frecuentemente se describe en términos de “bendiciones” y “maldiciones”.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Radioquinesis","Habilidad para manipular la radioactividad a través del espectro electromagnético, o generarla desde el propio cuerpo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Distorsionar la realidad","Habilidad para cambiar o manipular la realidad. Es un forma más avanzada que la Ilusión.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Proyección de pensamiento","Permite volver realidad sus deseos sin el uso de pociones o hechizos.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Proyección de escritura","Consiste en darle vida(hacer realidad) a lo que hemos escrito o en su caso estamos escribiendo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Sonoquinesis","Audioquinesis, sonoquinesis o ecoquinesis son los distintos nombres que recibe la habilidad de manipular mentalmente las ondas sonoras.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Cronoquinesis","Habilidad para afectar el flujo del tiempo, ralentizándolo, acelerándolo o incluso deteniéndolo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Hipnoquinesis","Habilidad para controlar los sueños de las personas y poder hacerles ver en su mente lo que se desee. También tiene este control sobre las pesadillas y el poder alterarlas a peor o mejor");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Combustión espontanea","Habilidada de crear de forma inesperada en un objeto y/o persona deseada la aparicion brusca de llamas;las cuales son muy intensas y en un lapso de tiempo muy corto el cuerpo queda completamente destruido y reducido a un pequeño montón de cenizas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transportación o viaje","Son habilidades que permiten la transportacion a largas o cortas distancias sin necesidad de un vehículo o el movimiento del cuerpo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Umbraquinesis","Habilidad para crear o usar la oscuridad, frecuentemente accediendo mentalmente a una dimensión de energía oscura");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Transportación eléctrica","Habilidad para viajar a través de los conductos eléctricos (tales como cables de poder, o líneas telefónicas), frecuentemente entrando a través de dispositivos como televisores, polos eléctricos, tomas de corriente o computadores.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Omnipresencia","Habilidad que consiste en la simultánea presencia en todas partes.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Dimensión de bolsillo","Habilidad para crear dimensiones de bolsillo temporales, o acceder a “pequeñas” dimensiones permanentes.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Creación de portal","Habilidad para crear agujeros de gusano en el tiempo o el espacio.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Invocación","Habilidad para invocar objetos o seres para la propia asistencia");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Velocidad sobrehumana","Habilidad para moverse más rápido que lo usual. En frecuentes ocasiones, aproximándose a la velocidad de la luz.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Teletransportación","Habilidad para moverse de un lugar a otro sin ocupar espacio o masa en el trayecto.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Orbitación","Habilidad de transportarse mediante luces celestes (partículas volátiles)");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Fluctuar","La capacidad de teletransportarse entre llamas");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Viajar por el tiempo","Habilidad para viajar a través del tiempo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Poderes físicos personales","Poderes que tienen algún efecto en la constitución física de un individuo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Sanación acelerada (factor de curación)","Habilidad para curar rápidamente de cualquier lesión. El tiempo de recuperación varía según el personaje, también puede resultar en inmortalidad o al menos en longevidad.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Desarrollo de un álter-ego","Habilidad para desarrollar un álter-ego interior o doble personalidad sea de forma natural o por medio de algo externo (rayos gamma, pociones especiales). Esta segunda personalidad tiene, aparentemente, superfuerza.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Bioquinesis","Habilidad para controlar la vida. Los Manipuladores Biológicos pueden curar, matar, alterar la composición del cuerpo y pueden hacer otras cosas relacionadas con el cuerpo vivo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Sustitución de partes del cuerpo","Habilidad para reemplazar una propia extremidad u otra parte del cuerpo por la misma extremidad u otra parte diferente. Tambien hacer que la parte del cuerpo se regenere, por ejemplo, que un brazo amputado vuelva a crecer.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Duplicación","Habilidad para crear réplicas (no clones) de uno mismo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Ecolocación","Habilidad para determinar la ubicación de objetos en el espacio mediante el uso de las reflexiones de las ondas sonoras, sean estas producidas por el sujeto o sonidos ambientales. (También conocida como Sentido Sonar).");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Sentidos aumentados (mejorados)","Aumento de percepción en los sentidos de la vista, el olfato, el gusto, el tacto y la audición.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Invisibilidad","Habilidad para mostrarse u ocultarse al ojo humano normal.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Invulnerabilidad","Inmunidad total o parcial a cualquier clase de daño.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Ingestión de materia","Habilidad para consumir cualquier clase de materia sin que esto provoque malestar o enfermedad en el sujeto.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Armadura natural","Una inusual, resistente y perdurable coraza externa de piel.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Armas naturales","Atributos físicos tales como garras, dientes afilados, púas, redes y otras cualidades usualmente asociadas con animales.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipulación de feromonas","La habilidad de generar y controlar las propias feromonas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Reflejos fotográficos","Habilidad para imitar cualquier acto atlético o movimiento de arte marcial luego de haberlo visto sólo una vez. En otros casos es la habilidadad para esquivar cualquier acto físico con mayor rapidez que la humana.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Envenenar","Habilidad para atacar a otros con una o más variedades de toxinas, con una amplia gama de diversos efectos");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Arma biológica natural/virogénesis","Habilidad que consiste en que la misma persona despida enfermedades, virus, o le cause algún otro tipo de mal a cualquier otro factor biológico, y lo restaure a voluntad o con asistencia.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Adaptación/evolución reactiva","Habilidad para desarrollar una resistencia o inmunidad a cualquier cosa que haya afectado o a la que haya estado expuesto el sujeto.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Autodetonación o explosión","Habilidad de explotar la propia masa corporal y volver a formarla. En otros casos consiste en liberar una gran cantidad de energía del cuerpo");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Separación","Habilidad para separar partes del propio cuerpo y hacer que actúen por su voluntad.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Fusión","Habilidad para fusionarse con otra persona. Esto da como resultado un ser completamente nuevo y más fuerte.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Manipular el cabello","Habilidad que permite utilizar el cabello como una extremidad más del cuerpo, usándolo tanto para atacar y defenderse.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Grito sónico","Habilidad para usar la propia voz de forma ofensiva o defensiva.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Reflejos sobrehumanos","Habilidad para reaccionar más rápido que un humano normal.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Fuerza sobrehumana","Fuerza física por encima de la normal sin necesidad de tener una massa corporal elevada.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Adherencia","Habilidad para aferrarse a objetos o superficies de diversas maneras y movilizarse sobre ellas");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Habilidades animales e insectos","Son hábilidades que se modifican en base a un animal o insecto concreto, como un lobo, un tigre o una araña. Además de ganar sus habilidades también se tienen sus debilidades, o mejor dicho, se adquiere parte del comportamiento del animal o insecto en si");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Longevidad","Capacidad de vivir más de lo normal, este poder puede deverse por provenir de una raza ajena a la humana, por mutaciones o por otros poderes como la sanación acelerada.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Agilidad sobrehumana","Habilidad para moverse con más soltura por un sitio, utilizando brazos y piernas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Regeneración celular","Este proceso puede darse de forma natural, pero la forma sobrenatural se da en un corto período de tiempo (de forma espontánea) se define como la restauración de tejidos dañados o perdidos, ya sean órganos o extremidades.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Curación","Habilidad que consiste en sanar lesiones fisicas de otros seres vivos atraves del tacto");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Respiracion de vacio","Habilidad para respirar en cualquier ambiente, pero este no es inmune a cualquier tipo de agente toxico.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Petrificacion","Es la habilidada de transformar cualquier cosa en piedra, esta puede ser emitida por la vista ,tacto,saliva o alguna otra forma que se les ocurra.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Inmunidad","Esta habilidad consiste en no poder ser dañado por cualquiera que sea la habilidad utilizada contra uno. ");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Omnilingüismo","Habilidad para descifrar cualquier lenguaje.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Omnisciencia","Capacidad de saberlo todo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Inteligencia sobrehumana","Inteligencia muy por encima del nivel de genio, frecuentemente acompañada por la habilidad de inventar increíble y avanzada tecnología, la super inteligencia puede deberse a un proceso natural ganado por el esfuerzo de la persona o por exposición a radiación o químicos que causan un extraño desarrollo cerebral");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Memoria sobrehumana","Capacidad para no olvidar ningún escrito, imagen, sonido, etc., asumidos anteriormente. También puede llamársele Mnemonismo. La diferencia entre la 1era es que se puede recordar todo lo percibido a voluntad, el mnemonismo no permite olvidar y no muestra un control sobre la memoria.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Memoria Recreativa","Capacidad para poder Manipular cualquier Recuerdo almacenado. pueden ser escritos, imágenes, sonidos incluso en concentraciones mayores manipular el tacto y los sentidos (vista, gusto, tacto, olfato y audición).");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Actitud intuitiva","Habilidad que permite conocer de forma precoz, el funcionamiento de sistemas complejos y poder usarlos o manipularlos.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Percepción extrasensorial (PES)","Las habilidades de percepción y comunicación extrasensorial.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Proyección astral","Habilidad para separar y controlar el propio cuerpo astral, este puede ser translucido o corporal.Normalmente el cuerpo astral no puede usar los poderes del cuerpo inconsciente, pero cuando se congue practica si se puede e incluso pueden proyectarse con el cuerpo consciente.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Clarividencia y clariaudiencia","Clarividencia es la habilidad para percibir eventos que están ocurriendo en otro lugar o sentir lugares que no están a la vista como si se estuviera presente. Frecuentemente permite ver sucesos futuros. La clariaudiencia es la habilidad auditiva equivalente a la clarividencia, permitiendo escuchar como si se estuviera en ese lugar. Otros sentidos remotos también pueden manifestarse de esta forma.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Conocimiento más allá de la propia dimensión","Habilidad para detectar y tomar conocimiento de acciones y eventos en otras dimensiones. Esto ocasionalmente es utilizado en comics como la toma de consciencia de la existencia del “cuarto muro” (un muro imaginario que separa el mundo de ficción del real) entre los personajes y el guionista o dibujante, o incluso, entre los personajes y los lectores.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Sentido del peligro","Habilidad para percibir el peligro personal. Es una forma limitada de precognicion.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Empatía","Habilidad para leer o sentir las emociones y sentimientos de otros. En algunos casos, los empáticos que desarrollan esta habilidad pueden proyectar su empatía a otros, haciendo así que estos compartan sus emociones.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Precognición/premonición","Habilidad para percibir el futuro. En ocasiones solamente se expresa en la forma de vagos sueños mientras se duerme, mientras que otras veces es clara y ocurre a voluntad, mientras se está despierto, o incluso pintándolo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES (" Psicometría","Habilidad para relatar detalles sobre la condición pasada o futura de un objeto, persona o locación, usualmente estando en contacto cercano a él/ella, o directamente mediante contacto físico.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Telepatía","Habilidad para comunicarse mentalmente con otros, rompiendo las barreras de la distancia. Generalmente, permite hablar en un lenguaje universal. Si el grado de dominio es alto, tambien puede canalizar los poderes y usarlos.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Asentamiento astral","Habilidad para crear una proyección astral para quedarse en el plano astral, usualmente en un lugar específico.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Control mental","Poder para controlar las acciones o el razonamiento de otra persona.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Posesión","Habilidad para tomar control del cuerpo de otras personas mediante la proyección astral, la transferencia de mente o transformar el cuerpo físico en un estado fantasmal y entrar en el cuerpo de otra persona. Una forma especializada de Control Mental.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Persuasión","Capacidad de hacer que otras personas realicen acciones, sin que éstas puedan negarse, mediante palabras con entonación imperativa, es decir, ordenándolas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Estallido psiónico","Habilidad para sobrecargar una mente ajena, luego de haber establecido un vínculo psiónico con la mente de esa persona, causando dolor, pérdida de memoria, inconsciencia, estado vegetativo o incluso la muerte.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Armas psíquicas","Habilidad para crear un arma, como un cuchillo o una granada, hecha de energía psiónica que puede dañar mentalmente y no físicamente.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Visión Rayos X","Puede ver atrás de las murallas, una persona común ve la muralla, pero con este poder, puede ver lo que esta pasando detrás de las cosas o dentro de ellas.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Visión láser","Permite disparar laser sin ser dañado através de los ojos. Esto se puede controlar o no dependiendo el tipo de visión de láser que le toque.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Visión telequinética","Uno de los poderes que pocas veces apareció, y que no se usó más debido posiblemente por su poca aceptabilidad. ");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Visión Compartida y Visión Remota","Es la habilidad de poder ver atraves de los ojos de los demas o en otros casos, hacer que los demas puedan ver lo que estamos viendo en ese momento.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Visión nocturna","Es la habilidada de poder ver en la oscuridad en los entornos que están en bajos niveles de iluminación.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Visión Termica","Es la habilidada de poder ver la temperatura de un cuerpo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Visión contaminable","Es como la visión láser, solo que dispara através de sus ojos la contaminación.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Volar ","Habilidad para alzarse desde el suelo, para navegar las corrientes de aire o volar por propia cuenta a través del aire. Las diferentes formas de volar incluyen:");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Ilusión","Habilidad para alterar o engañar las percepciones de otra persona. Usualmente visual, puede ser un efecto basado en la luz, basado en el sonido, un efecto producido al afectar la mente ajena, o cualquier otro efecto que cause el percibir cosas que no necesariamente son reales.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Polimorfismo","Habilidad para cambiar la apariencia o la estructura corporal temporalmente, así como alterar la de otros seres.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Mimetismo virtual","Aquellos movimientos basados y obtenidos de cosas más ficticias, son un mimetismo virtual.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Manipulación de la gravedad","Capacidad y habilidad, de controlar la gravedad sobre las cosas y sobre el mismo, sobre todo.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Habilidad o poder para hacer fuegos pirotécnicos","Es capaz de hacer estos fuegos Pirotécnicos apesar de que no sean mediante forma artificial.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Suerte exagerada","Algunos personajes tienen tanta suerte, que siempre les irá perfecto, o batirán cualquier cosa, conseguirán lo que quieren, y siempre los van a querer demasiado, si así lo desean.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Sinestesia","Poder de sentir las mismas emociones de un sentido en otros sentidos diferentes");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Aliento de fuego","Capacidad de formar fuego por los gases o el aliento desde su boca.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Aliento de hielo","Le dicen así por que hace congelar las cosas y no por que dispare hielo por la boca. Es como el aliento de fuego, solo que para enfriar.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Aliento tóxico","Capacidad de formar tóxinas através del aliento de su boca. En algunos villanos como en uno de Ben 10, podía exparcir algo tóxico que derretía materiales.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Súper aliento","Habilidad de que, al soplar, el soplido sea como un ventarrón de aire, llegando a impulsar objetos pesados a largas distancias.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Poderes definidos","Ciertos super poderes que son un conjunto de poderes ya mencionados. Estos podrían ser un poder en si que otorga ciertas habilidades de otros super poderes, o en este caso también podría ser solo un conjunto de super poderes.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Magia","Estos es un poder misterioso que no tiene explicación, esto puede ser divino, o místico, algo que podría derivar en una fuerza o habilidad sobrenatural.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Manipulación del espacio-tiempo","Aquí se entiende espacio y tiempo como una sola cosa, esto debido a que el espacio y el tiempo estan determinados para conformar la realidad, en este caso, se puede manipular la realidad, por estas dos bases, pero debido a que no podemos crear una realidad diferente con solo pensarlo, se le es considerado de espacio-tiempo.Los poderes que se tiene");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("El poder del absurdo","Este poder no esta definido, pero sería el hecho de poder crear o realizar cosas absurdas aún cuando evaden la lógica de la realidad.");
INSERT INTO `railway`.`t_poder` (`podtipo`, `poddescripcion`) VALUES ("Caricaturismo","Capacidad de actuar y hacer cosas como una caricatura de fantasía.");


INSERT INTO `railway`.`t_condicion` (`connom`) VALUES ('Preso');
INSERT INTO `railway`.`t_condicion` (`connom`) VALUES ('Libre');
INSERT INTO `railway`.`t_condicion` (`connom`) VALUES ('Desconocida');


INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AD", "Andorra" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AE", "Emiratos Árabes Unidos" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AF", "Afganistán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AG", "Antigua y Barbuda" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AI", "Anguila" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AL", "Albania" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AM", "Armenia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AN", "Antillas Neerlandesas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AO", "Angola" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AQ", "Antártida" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AR", "Argentina" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AS", "Samoa Americana" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AT", "Austria" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AU", "Australia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AW", "Aruba" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AX", "Islas Áland" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("AZ", "Azerbaiyán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BA", "Bosnia y Herzegovina" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BB", "Barbados" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BD", "Bangladesh" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BE", "Bélgica" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BF", "Burkina Faso" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BG", "Bulgaria" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BH", "Bahréin" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BI", "Burundi" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BJ", "Benin" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BL", "San Bartolomé" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BM", "Bermudas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BN", "Brunéi" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BO", "Bolivia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BR", "Brasil" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BS", "Bahamas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BT", "Bhután" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BV", "Isla Bouvet" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BW", "Botsuana" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BY", "Belarús" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("BZ", "Belice" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CA", "Canadá" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CC", "Islas Cocos" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CF", "República Centro-Africana" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CG", "Congo" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CH", "Suiza" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CI", "Costa de Marfil" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CK", "Islas Cook" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CL", "Chile" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CM", "Camerún" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CN", "China" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CO", "Colombia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CR", "Costa Rica" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CU", "Cuba" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CV", "Cabo Verde" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CX", "Islas Christmas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CY", "Chipre" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("CZ", "República Checa" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("DE", "Alemania" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("DJ", "Yibuti" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("DK", "Dinamarca" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("DM", "Domínica" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("DO", "República Dominicana" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("DZ", "Argel" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("EC", "Ecuador" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("EE", "Estonia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("EG", "Egipto" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("EH", "Sahara Occidental" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ER", "Eritrea" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ES", "España" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ET", "Etiopía" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("FI", "Finlandia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("FJ", "Fiji" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("FK", "Islas Malvinas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("FM", "Micronesia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("FO", "Islas Faroe" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("FR", "Francia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GA", "Gabón" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GB", "Reino Unido" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GD", "Granada" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GE", "Georgia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GF", "Guayana Francesa" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GG", "Guernsey" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GH", "Ghana" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GI", "Gibraltar" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GL", "Groenlandia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GM", "Gambia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GN", "Guinea" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GP", "Guadalupe" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GQ", "Guinea Ecuatorial" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GR", "Grecia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GS", "Georgia del Sur e Islas Sandwich del Sur" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GT", "Guatemala" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GU", "Guam" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GW", "Guinea-Bissau" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("GY", "Guayana" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("HK", "Hong Kong" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("HM", "Islas Heard y McDonald" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("HN", "Honduras" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("HR", "Croacia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("HT", "Haití" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("HU", "Hungría" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ID", "Indonesia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IE", "Irlanda" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IL", "Israel" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IM", "Isla de Man" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IN", "India" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IO", "Territorio Británico del Océano Índico" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IQ", "Irak" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IR", "Irán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IS", "Islandia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("IT", "Italia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("JE", "Jersey" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("JM", "Jamaica" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("JO", "Jordania" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("JP", "Japón" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KE", "Kenia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KG", "Kirguistán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KH", "Camboya" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KI", "Kiribati" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KM", "Comoros" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KN", "San Cristóbal y Nieves" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KP", "Corea del Norte" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KR", "Corea del Sur" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KW", "Kuwait" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KY", "Islas Caimán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("KZ", "Kazajstán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LA", "Laos" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LB", "Líbano" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LC", "Santa Lucía" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LI", "Liechtenstein" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LK", "Sri Lanka" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LR", "Liberia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LS", "Lesotho" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LT", "Lituania" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LU", "Luxemburgo" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LV", "Letonia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("LY", "Libia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MA", "Marruecos" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MC", "Mónaco" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MD", "Moldova" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ME", "Montenegro" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MG", "Madagascar" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MH", "Islas Marshall" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MK", "Macedonia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ML", "Mali" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MM", "Myanmar" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MN", "Mongolia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MO", "Macao" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MQ", "Martinica" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MR", "Mauritania" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MS", "Montserrat" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MT", "Malta" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MU", "Mauricio" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MV", "Maldivas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MW", "Malawi" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MX", "México" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MY", "Malasia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("MZ", "Mozambique" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NA", "Namibia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NC", "Nueva Caledonia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NE", "Níger" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NF", "Islas Norkfolk" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NG", "Nigeria" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NI", "Nicaragua" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NL", "Países Bajos" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NO", "Noruega" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NP", "Nepal" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NR", "Nauru" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NU", "Niue" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("NZ", "Nueva Zelanda" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("OM", "Omán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PA", "Panamá" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PE", "Perú" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PF", "Polinesia Francesa" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PG", "Papúa Nueva Guinea" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PH", "Filipinas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PK", "Pakistán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PL", "Polonia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PM", "San Pedro y Miquelón" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PN", "Islas Pitcairn" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PR", "Puerto Rico" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PS", "Palestina" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PT", "Portugal" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PW", "Islas Palaos" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("PY", "Paraguay" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("QA", "Qatar" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("RE", "Reunión" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("RO", "Rumanía" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("RS", "Serbia y Montenegro" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("RU", "Rusia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("RW", "Ruanda" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SA", "Arabia Saudita" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SB", "Islas Solomón" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SC", "Seychelles" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SD", "Sudán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SE", "Suecia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SG", "Singapur" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SH", "Santa Elena" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SI", "Eslovenia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SJ", "Islas Svalbard y Jan Mayen" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SK", "Eslovaquia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SL", "Sierra Leona" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SM", "San Marino" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SN", "Senegal" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SO", "Somalia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SR", "Surinam" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ST", "Santo Tomé y Príncipe" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SV", "El Salvador" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SY", "Siria" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("SZ", "Suazilandia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TC", "Islas Turcas y Caicos" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TD", "Chad" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TF", "Territorios Australes Franceses" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TG", "Togo" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TH", "Tailandia" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TH", "Tanzania" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TJ", "Tayikistán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TK", "Tokelau" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TL", "Timor-Leste" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TM", "Turkmenistán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TN", "Túnez" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TO", "Tonga" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TR", "Turquía" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TT", "Trinidad y Tobago" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TV", "Tuvalu" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("TW", "Taiwán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("UA", "Ucrania" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("UG", "Uganda" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("US", "Estados Unidos de América" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("UY", "Uruguay" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("UZ", "Uzbekistán" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("VA", "Ciudad del Vaticano" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("VC", "San Vicente y las Granadinas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("VE", "Venezuela" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("VG", "Islas Vírgenes Británicas" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("VI", "Islas Vírgenes de los Estados Unidos de América" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("VN", "Vietnam" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("VU", "Vanuatu" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("WF", "Wallis y Futuna" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("WS", "Samoa" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("YE", "Yemen" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("YT", "Mayotte" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ("ZA", "Sudáfrica" );
INSERT INTO `railway`.`t_pais` (`paicod`, `painom`) VALUES ('FC', 'Ficticio');


INSERT INTO `railway`.`t_rol` (`rolafinidad`) VALUES ('Heroe');
INSERT INTO `railway`.`t_rol` (`rolafinidad`) VALUES ('Villano');
INSERT INTO `railway`.`t_rol` (`rolafinidad`) VALUES ('Antiheroe');
INSERT INTO `railway`.`t_rol` (`rolafinidad`) VALUES ('Sin motivaciones');
INSERT INTO `railway`.`t_rol` (`rolafinidad`) VALUES ('Indeterminado');


INSERT INTO `railway`.`t_vehiculo` (`vehnom`, `vehdescripcion`, `vehcodigo`) VALUES ('Silla de ruedas', 'El usuario define la dirección con la meditación. Si uno empieza a relajar los músculos y respirar profundamente, se entra en un estado de meditación. Y cuando suben los niveles de concentración, empieza a avanzar la silla', 'VCH');
INSERT INTO `railway`.`t_vehiculo` (`vehnom`, `vehdescripcion`, `vehcodigo`) VALUES ('X-Jet', 'es un avión ficticio que aparece en los cómics estadounidenses publicados por Marvel Comics. El avión está representado por el equipo de superhéroes X-Men. Ha habido varias encarnaciones de esta nave a lo largo de los años, con Cíclope y Tormenta como los principales pilotos.', 'XJT');
INSERT INTO `railway`.`t_vehiculo` (`vehnom`, `vehdescripcion`, `vehcodigo`) VALUES ('BLITZ BUGGY', 'Podemos ver a Namor a bordo de un jeep que el mismo construyo', 'VCH');
INSERT INTO `railway`.`t_vehiculo` (`vehnom`, `vehdescripcion`, `vehcodigo`) VALUES ('Ninguno', 'No usa vehiculo', 'NOT');
INSERT INTO `railway`.`t_vehiculo` (`vehnom`, `vehdescripcion`, `vehcodigo`) VALUES ('Motocicleta', 'Vehiculo a motor de dos ruedas', 'MOT');

INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Warren Kenneth Worthington III",1,"Ángel ",4,4,2,226,5,"https://static.wikia.nocookie.net/xmenmovies/images/1/15/AngelFP.jpg/revision/latest/scale-to-width-down/350?cb=20160422202636");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Wanda Maximoff",1,"Bruja Escarlata",5,4,2,226,6,"https://media.vandalsports.com/i/1706x960/7-2022/202271815330_1.jpg.webp");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Charles Francis Xavier",1,"Charles Xavier",1,1,2,75,8,"https://images.hindustantimes.com/img/2022/03/25/400x225/X-Men-Apocalypse-James-McAvoy_1648208390595_1648208403795.jpg");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Scott Summers",1,"Cíclope",1,2,2,226,9,"https://i0.wp.com/wipy.tv/wp-content/uploads/2021/06/el-mcu-no-esta-honrando-a-hulk-1.jpeg?resize=768%2C461&ssl=1");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Piotr Peter Nikolaievitch Rasputin",1,"Coloso ",1,2,2,187,7,"https://dam.smashmexico.com.mx/wp-content/uploads/2020/03/deadpool-coloso-768x512.jpg");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Remy Etienne LeBeau",1,"Gambito ",1,2,2,73,6,"https://sm.ign.com/t/ign_es/feature/g/gambit-exp/gambit-explained-who-is-the-x-men-character_1nw3.1280.jpg");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Robert Louis Bobby Drake",1,"Iceman ",1,4,2,226,1,"https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Iceman.png/220px-Iceman.png");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Jean Elaine Grey Summers",1,"Jean Grey",3,2,2,226,7,"https://static.wikia.nocookie.net/marveldatabase/images/4/4d/A.X.E._Judgment_Day_Vol_1_3_Women_of_A.X.E._Variant_Textless.jpg/revision/latest/scale-to-width-down/323?cb=20220711112817");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Jubilation Lee",1,"Júbilo",4,2,2,226,9,"https://i0.wp.com/codigoespagueti.com/wp-content/uploads/2021/12/My-Hero-Academia-Himiko-Toga-te-dejara-sin-palabras-con-este-bellisimo-cosplay-body-paint-7.jpg?resize=1280%2C720&quality=80&ssl=1");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Alyosha Kravinoff",1,"Kraven el Cazador",5,4,2,240,5,"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/kraven-cazador-peliculas-spider-man-1539178191.jpg?crop=1.00xw:0.892xh;0,0&resize=768:*");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Erik Lehnsherr",1,"Magneto",2,4,2,55,8,"https://static.wikia.nocookie.net/universo-cinematografico-de-xmen/images/5/5c/Magneto1.jpg/revision/latest/scale-to-width-down/333?cb=20160901214220&path-prefix=es");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Dr. Nathaniel Essex",1,"Mr. Siniestro",2,4,2,226,3,"https://dam.smashmexico.com.mx/wp-content/uploads/2020/05/mr-sinister-villano-pelicula-gambit-cancelada-cover-768x512.jpg");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Raven Darkhölme",1,"Mystique",2,4,2,226,2,"https://assets.mycast.io/characters/mistique-3660315-normal.jpg?1632203682");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Namor McKenzie",1,"Namor",3,3,2,226,6,"https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/NAMOR1cover-CMYKcrop.jpg/220px-NAMOR1cover-CMYKcrop.jpg");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Ellie Phimister",1,"Negasonic Teenage Warhead",1,2,2,226,8,"https://i.ytimg.com/vi/tgg4y9_rk4E/hqdefault.jpg");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Kurt Szards",1,"Nightcrawler",3,4,2,55,9,"https://static.wikia.nocookie.net/xmen9260/images/0/0d/X2nightcrawl.jpg/revision/latest/scale-to-width-down/350?cb=20190717172237&path-prefix=es");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("St. John Allerdyce",1,"Pyro",5,5,2,14,3,"https://static.wikia.nocookie.net/xmenmovies/images/e/ef/Pyro_%28X-Men-_The_Last_Stand%29.jpg/revision/latest/scale-to-width-down/350?cb=20150611182241");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Pietro Maximoff",1,"Quicksilver",1,4,2,226,2,"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2020/06/hipertextual-evan-peters-quicksilver-x-men-apareceria-wandavision-2020612247.jpg?resize=700%2C448&quality=60&strip=all&ssl=1");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("Víctor Creed",1,"Sabretooth",2,4,2,226,1,"https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Sabretooth_%28Victor_Creed%29.jpg/220px-Sabretooth_%28Victor_Creed%29.jpg");
INSERT INTO railway.t_mutantes (mutnom, mutactivo, mutapodo, rolid, vehid, conid, paiid, podmutid, mutimg) VALUES ("James Howlett/Logan",1,"Wolverine",3,2,2,226,7,"https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2019/02/hipertextual-disney-busqueda-nuevo-wolverine-integrarlo-universo-cinematografico-marvel-2019958269-scaled.jpg?w=1560&quality=60&strip=all&ssl=1");

UPDATE `railway`.`t_mutantes` SET `mutimg` = 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/styles/hc_1440x810/public/media/image/2019/03/magneto.jpg?itok=u3-bZu95' WHERE (`mutid` = '11');
UPDATE `railway`.`t_mutantes` SET `mutimg` = 'https://bbts1.azureedge.net/images/p/full/2020/12/76b0440b-4874-4880-b602-77a2f123ce5d.jpg' WHERE (`mutid` = '16');
UPDATE `railway`.`t_mutantes` SET `mutimg` = 'http://pm1.narvii.com/6579/a898ffbeb6937693b468bf940ce13d5bfe3b4677_00.jpg' WHERE (`mutid` = '1');
UPDATE `railway`.`t_mutantes` SET `mutimg` = 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/05/Pyro-contemplates-the-flame.jpg?q=50&fit=crop&w=750&dpr=1.5' WHERE (`mutid` = '17');

INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('1', '2');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('1', '11');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('1', '12');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('1', '13');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('2', '14');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('2', '15');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('2', '16');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('2', '17');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('3', '18');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('3', '19');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('4', '20');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('4', '21');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('5', '22');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('5', '23');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('6', '24');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('7', '26');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('8', '27');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('9', '28');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('9', '29');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('10', '30');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('11', '31');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('11', '32');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('12', '33');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('12', '34');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('13', '36');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('14', '37');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('14', '38');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('14', '39');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('14', '40');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('15', '41');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('16', '42');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('17', '101');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('17', '102');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('17', '103');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('18', '105');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('18', '106');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('19', '107');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('19', '102');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('20', '108');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('20', '109');
INSERT INTO `railway`.`t_poder_mutante` (`podid`, `mutid`) VALUES ('20', '110');
UPDATE `railway`.`t_vehiculo` SET `vehnom` = 'Pajaro negro', `vehimg` = 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/styles/hc_1440x810/public/media/image/2019/02/X-Men-Blackbird1.jpg?itok=VdY2_Nh1' WHERE (`vehid` = '2');
UPDATE `railway`.`t_vehiculo` SET `vehimg` = 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/styles/hc_1440x810/public/media/image/2013/02/210781-bryan-singer-muestra-sillas-profesor-xavier.jpg?itok=65FdMpNR' WHERE (`vehid` = '1');
UPDATE `railway`.`t_vehiculo` SET `vehdescripcion` = 'El \"Blitz-Buggy\" podría alcanzar velocidades superiores a las de los jeeps militares que se construyeron en la década de 1940 (el vehículo militar blindado estadounidense promedio de ese tamaño alcanza velocidades máximas entre 40 y 56 MPH), cuyo rango superior se desconoce.', `vehimg` = 'https://static.wikia.nocookie.net/marveldatabase/images/8/8c/Namor%27s_Jeep_from_Marvel_Mystery_Comics_Vol_1_22_0001.jpg/revision/latest?cb=20110501194746' WHERE (`vehid` = '3');
UPDATE `railway`.`t_vehiculo` SET `vehdescripcion` = 'Vehiculo a motor de dos ruedas.' WHERE (`vehid` = '5');
UPDATE `railway`.`t_vehiculo` SET `vehdescripcion` = 'No usa vehiculo,(N/A)', `vehimg` = 'https://supercurioso.com/wp-content/uploads/2016/01/supervelocidad.jpg' WHERE (`vehid` = '4');
UPDATE `railway`.`t_vehiculo` SET `vehimg` = 'https://cmro.travis-starnes.com/images/equipment/blitz-buggy.jpg' WHERE (`vehid` = '3');